name: 'DisSLackNoti'
description: 'Send notification to Discord and Slack'
branding:
  icon: 'bell'  
  color: 'green'  
author: 'Angel Scutari'
inputs:
  githubToken:
    description: 'Github API token'
    required: true
  slackToken:
    description: 'Slack API token'
    required: false
  messageType:
    description: 'Type of message to send'
    required: true
  discordWebhookUrl:
    description: 'Webhook URL for discord'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'