name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:
  
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Notification to slack
      uses: OSCloudysky/UniNotify@v1
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        messageType: 'slack' 
        slackToken: ${{ secrets.SLACK_API_TOKEN }}
        slackChannel: ${{ secrets.SLACK_CHANNEL}}

    - name: Send notification to Discord
      uses: OSCloudysky/UniNotify@v1
      if: always()
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        messageType: 'discord'
        discordWebhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}